# Generated by Django 3.2.4 on 2021-07-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_verbose_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verbose_name',
            new_name='displayname',
        ),
    ]
