# Generated by Django 3.2.4 on 2021-07-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_width',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default/default_avatar.jpg', null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
