# Generated by Django 3.2.4 on 2021-07-14 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20210710_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, editable=False, related_name='mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
