# Generated by Django 3.2.4 on 2021-07-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_post_mentioned_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_checked_mentions',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
