# Generated by Django 3.2.4 on 2021-07-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_user_last_checked_mentions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_checked_mentions',
        ),
        migrations.AddField(
            model_name='user',
            name='mentions_since_last_checked',
            field=models.PositiveIntegerField(default=0, verbose_name='Mentions since last checked'),
        ),
    ]
