# Generated by Django 3.2.4 on 2021-07-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch'), ('JP', '日本語')], default='EN', max_length=2, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('theme-light', 'Light Mode'), ('theme-dark', 'Dark Mode')], default='theme-light', max_length=20, verbose_name='Theme'),
        ),
    ]
