# Generated by Django 3.2.4 on 2021-07-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20210717_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('_theme_light', 'Light Mode'), ('_theme_dark', 'Dark Mode')], default='_theme_light', max_length=20, verbose_name='Theme'),
        ),
    ]
