# Generated by Django 3.2.4 on 2021-07-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_alter_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('DE', 'Deutsch'), ('JA', '日本語')], default='EN', max_length=2, verbose_name='Language'),
        ),
    ]
