# Generated by Django 3.2.4 on 2021-07-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='error: post initialized without text', max_length=140),
        ),
    ]
