# Generated by Django 3.2.4 on 2021-07-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_rename_recipients_directmessage_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DMs_since_last_checked',
            field=models.PositiveIntegerField(default=0, verbose_name='DMs since last checked'),
        ),
    ]
