# Generated by Django 3.2.4 on 2021-07-23 21:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_alter_directmessage_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
