# Generated by Django 3.2.4 on 2021-07-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0029_auto_20210724_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='replies', to='network.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_liked_posts',
            field=models.BooleanField(default=True, verbose_name='Show Liked Posts'),
        ),
    ]
