# Generated by Django 3.2.4 on 2021-07-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0030_auto_20210725_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='post-images'),
        ),
    ]
