# Generated by Django 3.2.4 on 2021-08-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0034_user_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='post-images', verbose_name='Image'),
        ),
    ]
