# Generated by Django 3.2.4 on 2021-08-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0037_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('ja', '日本語')], default='en', max_length=10, verbose_name='Language'),
        ),
    ]
