# Generated by Django 3.2.4 on 2021-08-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0039_auto_20210811_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
