# Generated by Django 3.2.6 on 2021-08-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0040_auto_20210814_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/avatars/default/default_avatar.jpg', null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
